version: '3'
services:
  mongo:
    container_name: mongo-container
    image: mongo:4
    logging:
      driver: none
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
  api:
    container_name: api-container
    image: node:14
    working_dir: /usr/www/keep-note-microservice
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    environment:
      - MONGO_URL=mongodb://mongo:27017/noteDb
    volumes:
      - ./dist/:/usr/www/keep-note-microservice/dist/
      - ./package.json:/usr/www/keep-note-microservice/package.json
    ports:
      - '5050:5050'
    links:
      - mongo
